import shutil
import random
import math
import time

try:
    import torch
except ImportError:
    torch = None

from expman import Experiment

def run_experiment(run_config):
    """
    Runs a single experiment training loop with the given config.
    """
    lr = run_config.get("lr", 0.001)
    batch_size = run_config.get("batch_size", 32)
    epochs = run_config.get("epochs", 10)
    model_name = run_config.get("model_name", "model")
    
    # Initialize Experiment
    # We use the same experiment name for grouping, but different run names/autogenerated
    # Or strict run names passed in config
    run_name = run_config.get("run_name", None)
    
    exp = Experiment("test_experiment", run_name=run_name)
    exp.log_params(run_config)
    
    print(f"Starting Run: {exp.run_name} | Config: {run_config}")
    
    # Simulate Training Loop
    for epoch in range(epochs):
        # Simulate metrics
        # Different curve shapes based on config to make them distinct
        noise = random.random() * 0.05
        if lr > 0.005: # "Fast" learning but noisy
            loss = max(0, 2.5 * math.exp(-epoch/3) + noise)
            acc = min(1.0, 1 - math.exp(-epoch/3) - noise/2)
        else: # "Slow" stable learning
            loss = max(0, 3.0 * math.exp(-epoch/5) + noise)
            acc = min(1.0, 1 - math.exp(-epoch/5) - noise/2)
            
        metrics = {"epoch": epoch, "lr": lr}
        
        metric_type = run_config.get("metric_type", "standard")
        if metric_type == "standard":
             metrics["loss"] = loss
             metrics["accuracy"] = acc
        elif metric_type == "score":
             # Different keys: Score (higher better), Latency (lower better)
             metrics["score"] = acc * 100
             metrics["latency_ms"] = 50 + noise * 1000
        
        exp.log_metrics(metrics, step=epoch)
        time.sleep(0.1) # Simulate work
        
    # Save Model (if torch available)
    if torch:
        print("Saving mock model...")
        # Create a dummy model just for saving
        model = torch.nn.Linear(100, 10)
            
        exp.save_model(model, "final_model.pt", input_size=(1, 100))
    
    print(f"Finished Run: {exp.run_name}")
    print("-" * 30)

def main():
    # Clean up previous tests
    shutil.rmtree("experiments/test_experiment", ignore_errors=True)
    
    # Run 1: High LR, ResNet
    config1 = {
        "run_name": "run_fast_resnet",
        "lr": 0.01,
        "batch_size": 64,
        "epochs": 15,
        "model_name": "mlp_advanced",
        "optimizer": "sgd",
        "metric_type": "standard"
    }
    run_experiment(config1)
    
    # Run 2: Low LR, Simple MLP
    config2 = {
        "run_name": "run_slow_mlp",
        "lr": 0.001,
        "batch_size": 32,
        "epochs": 20,
        "model_name": "mlp_basic",
        "optimizer": "adam",
        "metric_type": "score"
    }
    run_experiment(config2)

if __name__ == "__main__":
    main()
